version: '3.9'
services:
  client:
    build: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/app
      - /usr/app/build
      - /usr/app/node_modules
  joke:
    build: joke
    ports:
      - '4000:4000'
    volumes:
      - ./joke:/usr/app
      - /usr/app/node_modules
  leaderboard:
    build: leaderboard
    ports:
      - '4001:4001'
    volumes:
      - ./leaderboard:/usr/app
      - /usr/app/node_modules
  comments:
    build: comments
    ports:
      - '4002:4002'
    volumes:
      - ./comments:/usr/app
      - /usr/app/node_modules
  event-bus:
    build: event-bus
    volumes:
      - ./event-bus:/usr/app
      - /usr/app/node_modules
  
  mongodb:
    image: mongo:latest
    volumes:
      - dadJokeRankings-data:/data/db
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  dadJokeRankings-data: